### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by mikkoyli** [moshekaplan/FuzzImageMagick#1]
I din't find licence file. It would be nice to know what is licence of these sample files.

**Comment by moshekaplan** [comment]
Unfortunately, the sample files are not released under any specific license. Most of the samples were either based on test cases derived from US-CERT BFF - which is based on the [GPL-licensed ImageMagic](https://github.com/CERTCC-Vulnerability-Analysis/certfuzz/issues/6). Other samples were derived from files found from Google searches.
