### ISSUE TITLE
PROGRAM ABORT : No instrumentation detected on Mac OSX

### ISSUE THREAD

**Issue by greg5678** [moshekaplan/FuzzImageMagick#3]
I'm trying to fuzz imagemagick on MacOSX. I have compiled afl-fuzz but I keep getting these errors. What am I doing wrong? I compiled ImageMagick with afl-fuzz but it says "Looks like the target binary is not instrumented!".

So I ran these commands
[code]CC=afl-clang-fast CXX=afl-clang-fast++ ./configure && make[/code]
[code]AFL_USE_ASAN=1 AFL_HARDEN=1 CC=afl-clang-fast CXX=afl-clang-fast++ ./configure --with-bzlib=no --with-djvu=no --with-dps=no --with-fftw=no --with-fpx=no --with-fontconfig=no --with-freetype=no --with-gvc=no --with-jbig=no --with-jpeg=no --with-lcms=no --with-lqr=no --with-lzma=no --with-openexr=no --with-openjp2=no --with-pango=no --with-png=no --with-tiff=no --with-wmf=no --with-x=no --with-xml=no --with-zlib=no --enable-hdri=no --enable-shared=no && AFL_USE_ASAN=1 AFL_HARDEN=1 make  && AFL_USE_ASAN=1 AFL_HARDEN=1 sudo make install[/code]
[code]afl-fuzz -m none -i "samples" -o "imagemagick_fuzz_results" magick @@ /dev/null[/code]
but it gave me these errors.
[code]sudo afl-fuzz -m none -i "samples" -o "imagemagick_fuzz_results" magick @@ /dev/null
afl-fuzz 2.28b by lcamtuf@google.com
[+] You have 4 CPU cores and 3 runnable tasks (utilization: 75%).
[+] Try parallel jobs - see /usr/local/share/doc/afl/parallel_fuzzing.txt.
[_] Setting up output directories...
[_] Scanning 'samples'...
[+] No auto-generated dictionary tokens to reuse.
[_] Creating hard links for all input files...
[_] Validating target binary...

[-] Looks like the target binary is not instrumented! The fuzzer depends on
    compile-time instrumentation to isolate interesting test cases while
    mutating the input data. For more information, and for tips on how to
    instrument binaries, please see /usr/local/share/doc/afl/README.

```
When source code is not available, you may be able to leverage QEMU
mode support. Consult the README for tips on how to enable this.
(It is also possible to use afl-fuzz as a traditional, "dumb" fuzzer.
For that, you can use the -n option - but expect much worse results.)
```

[-] PROGRAM ABORT : No instrumentation detected
         Location : check_binary(), afl-fuzz.c:6836[/code]

**Comment by moshekaplan** [comment]
Given that this is not an issue with the samples or submission script, this might be better posted at the afl-users Google group: https://groups.google.com/forum/#!forum/afl-users
